project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - home.qmd
          - about.qmd
      - section: "Layout"
        contents:
          - home.qmd
          - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true