project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    title: "Atelier de Datos Culturales"
    search: true
    contents:
      - index.qmd
      - section: "Día 1 - Fabricación de datos"
        contents:
          - Día_uno.qmd
          - Actividad_1.1.qmd
          - Actividad_1.2.qmd
          
      - section: "Día 2 - Análisis y visualización"
        contents:
          - Día_dos.qmd
          - Actividad_2.1.qmd
          - Actividad_2.2.qmd
      - contacto.qmd
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true