project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - about.qmd
      - section: "Layout"
        contents:
          - home.qmd
          - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true